// AUTO-GENERATED from shared/cards/schemas.json — do not edit; run `npm run generate:cards`

import { z } from 'zod'

export const summaryCardSchema = z.object({ "content": z.union([z.string(), z.null()]).describe("One-paragraph summary").default(null), "key_points": z.union([z.array(z.string()), z.null()]).describe("Bullet points highlighting key facts").default(null), "title": z.string().min(1).describe("Short title for the summary card"), "type": z.literal("summary") }).describe("A concise overview of the answer for the user.")

export const legalBasisCardSchema = z.object({ "article": z.union([z.string(), z.null()]).describe("Relevant article or paragraph number").default(null), "law": z.string().min(1).describe("Name of the law, regulation, or OIB Richtlinie"), "original_text": z.union([z.string(), z.null()]).describe("Literal excerpt from the source, if available").default(null), "section": z.union([z.string(), z.null()]).describe("Relevant section or chapter").default(null), "summary": z.union([z.string(), z.null()]).describe("Plain-language summary of the legal relevance").default(null), "type": z.literal("legal_basis") }).describe("A legal norm, regulation, or OIB Richtlinie that grounds the answer.")

export const projectProfilePatchCardSchema = z.object({ "patch": z.array(z.any()), "preview": z.array(z.any()).describe("One row per changed field; use \"—\" for before when the fact was previously unknown"), "rationale": z.string().describe("One or two sentences: what was learned in this conversation and why it changes the brief"), "title": z.string().describe("Short action title, e.g. \"Projektkontext aktualisieren: Fluchtniveau\""), "type": z.literal("project_profile_patch").default("project_profile_patch") }).describe("Propose an update to the project brief (hard project facts) — applied only if the user accepts.")

export const requirementChecklistCardSchema = z.object({ "items": z.array(z.any()).min(1).describe("The requirements, in reading order"), "note": z.union([z.string(), z.null()]).describe("Optional clarification").default(null), "reference": z.union([z.any(), z.null()]).describe("Overall source when items share one").default(null), "title": z.string().min(1).describe("Title, e.g. 'Anforderungen GK 4 – Brandschutz'"), "type": z.literal("requirement_checklist") }).describe("A requirement checklist: several pass/fail criteria for one question.\n\nEmit when an answer boils down to a list of criteria read against the\nproject ('Was muss ich für GK 4 erfüllen?', 'Ist das Bauansuchen\nvollständig?'). Each item carries its own verdict and, where possible, its\nown norm reference; unknown items use status 'needs_input' — never a guess.")

export const comparisonTableCardSchema = z.object({ "note": z.union([z.string(), z.null()]).describe("Optional clarification").default(null), "options": z.array(z.string()).min(2).describe("Column headers, e.g. ['GK 4', 'GK 5']"), "recommendation": z.union([z.string(), z.null()]).describe("Overall recommendation, if the answer implies one").default(null), "reference": z.union([z.any(), z.null()]).describe("Source grounding the compared values").default(null), "rows": z.array(z.any()).min(1).describe("The compared criteria"), "title": z.string().min(1).describe("Title, e.g. 'GK 4 vs. GK 5 – Anforderungen'"), "type": z.literal("comparison_table") }).describe("A side-by-side comparison of a small number of options.\n\nEmit when the user weighs alternatives (GK 4 vs GK 5, two escape-route\nvariants, Holzbau vs Massivbau requirements). Options are columns, criteria\nare rows; values are short strings the model already grounded in the\nanswer. Optionally highlight the favoured option per row and name an\noverall recommendation.")

export const buildingSectionCardSchema = z.object({ "markers": z.union([z.array(z.any()), z.null()]).describe("Reference lines: Fluchtniveau, GK/Hochhaus").default(null), "note": z.union([z.string(), z.null()]).describe("Optional clarification").default(null), "reference": z.any().describe("Source of the threshold heights"), "storeys": z.array(z.any()).describe("Storeys bottom-to-top; basements flagged below_grade"), "title": z.string().min(1).describe("Title, e.g. 'Gebäudeschnitt – Höhenprüfung'"), "type": z.literal("building_section") }).describe("A to-scale building cross-section (schematic) drawn from storey heights.\n\nEmit for height/Gebäudeklasse/Fluchtniveau questions where seeing the\nbuilding against threshold lines helps (e.g. 'liege ich unter der GK4-Grenze?\nFluchtniveau bei 9,8 m'). Draws stacked storeys, the ground line, and dashed\nmarker lines (Fluchtniveau, GK/Hochhaus limits) with labels.")

export const stairDiagramCardSchema = z.object({ "comfort_note": z.union([z.string(), z.null()]).describe("Result of the 2×Steigung + Auftritt comfort check").default(null), "reference": z.any().describe("Source of the step-geometry limits"), "riser_count": z.number().int().gt(0).describe("Number of steps in the flight (drawn)"), "riser_height": z.any().describe("Steigung (rise) per step; typical limit <= 18 cm"), "title": z.string().min(1).describe("Title, e.g. 'Treppenlauf – Steigungsverhältnis'"), "tread_depth": z.any().describe("Auftritt (going) per step; typical limit >= 28 cm"), "type": z.literal("stair_diagram"), "width": z.any().describe("Nutzbare Laufbreite; limit depends on Gebäudeklasse") }).describe("A staircase drawn to scale (schematic section) with step-geometry checks.\n\nEmit for stair questions (e.g. 'passt eine Treppe mit 17 Stufen, 18 cm\nSteigung, 27 cm Auftritt, 100 cm breit?'). Draws the step profile to scale\nand checks riser/going/width and the comfort rule (2×Steigung + Auftritt ≈\n59–65 cm) against OIB 4.")

export const dimensionDiagramCardSchema = z.object({ "dimensions": z.array(z.any()).describe("The measured dimensions to annotate on the schematic"), "note": z.union([z.string(), z.null()]).describe("Optional clarification").default(null), "reference": z.any().describe("Source of the dimension limits (e.g. OIB 4 / ÖNORM B 1600)"), "shape": z.enum(["door","ramp","corridor","turning_circle","threshold","parking_space"]).describe("Which schematic template to draw"), "title": z.string().min(1).describe("Title, e.g. 'Rampe – Neigung & Breite'"), "type": z.literal("dimension_diagram") }).describe("A parametric accessibility/geometry schematic with dimension arrows.\n\nEmit for clearance questions (door width, ramp gradient, turning circle,\ncorridor width, threshold). The renderer picks a prebuilt template for\n`shape` and draws each dimension arrow where it is measured, coloured by\nstatus — preventing the Stocklichte-vs-Durchgangslichte misread.")

export const setbackPlanCardSchema = z.object({ "building_depth_m": z.number().gt(0).describe("Building footprint depth in metres"), "building_width_m": z.number().gt(0).describe("Building footprint width in metres"), "parcel_depth_m": z.number().gt(0).describe("Parcel depth in metres (drawn to scale)"), "parcel_width_m": z.number().gt(0).describe("Parcel width in metres (drawn to scale)"), "reference": z.any().describe("Source of the setback requirements"), "sides": z.array(z.any()).describe("Required/actual distance per parcel edge"), "title": z.string().min(1).describe("Title, e.g. 'Abstandsflächen – Lageplan'"), "type": z.literal("setback_plan") }).describe("A top-down site plan (schematic): parcel, footprint, and setback envelopes.\n\nEmit for Abstandsflächen/Bauwich questions ('hält das Gebäude die Abstände\nein?'). Draws the parcel, the required-setback envelope, and the building\nfootprint, with a distance arrow per side coloured by status.")

export const egressDiagramCardSchema = z.object({ "exit_label": z.union([z.string(), z.null()]).describe("Label for the path end/exit").default("Treppenhaus"), "reference": z.any().describe("Source of the escape-length limit (OIB 2)"), "segments": z.array(z.any()).describe("Path runs from the worst-case point to the exit, in order"), "start_label": z.union([z.string(), z.null()]).describe("Label for the path start").default("ungünstigster Punkt"), "title": z.string().min(1).describe("Title, e.g. 'Fluchtweg – Gehweglänge'"), "total_length": z.any().describe("Sum of segment lengths vs the OIB limit (e.g. <= 40 m)"), "type": z.literal("egress_diagram") }).describe("A schematic escape-route (Fluchtweg) path with the total length checked.\n\nEmit for escape-route-length questions ('ist der Fluchtweg mit 12 m + 26 m\nzulässig?'). Draws the path segment-by-segment from the worst-case point to\nthe exit and checks the total against the OIB 2 limit (typically 40 m).")

export const daylightIncidenceCardSchema = z.object({ "glass_area": z.any().describe("Lichteintrittsfläche (m²) vs the ≥10% requirement"), "note": z.union([z.string(), z.null()]).describe("Optional clarification").default(null), "obstruction": z.union([z.any(), z.null()]).describe("Any object intruding into the 45° light cone").default(null), "reference": z.any().describe("Source of the daylight requirement (OIB 3)"), "room_floor_area_m2": z.union([z.number(), z.null()]).describe("Aufenthaltsraum floor area in m²").default(null), "title": z.string().min(1).describe("Title, e.g. 'Belichtung – freier Lichteinfall'"), "type": z.literal("daylight_incidence"), "window_head_height_m": z.union([z.number(), z.null()]).describe("Window head (Sturz) height in metres").default(null), "window_sill_height_m": z.union([z.number(), z.null()]).describe("Sill (Parapet) height in metres").default(null) }).describe("A daylight (Belichtung) schematic: the 45° free-light line vs obstructions.\n\nEmit for daylight/Belichtung questions (OIB 3). Draws a window section, the\n45° free-light-incidence line from the window's lower edge, any obstruction,\nand a glass-area-vs-floor-area check. The renderer does the 45° geometry —\nthe model supplies distances/heights only.")

export const guardrailCheckCardSchema = z.object({ "bottom_gap": z.union([z.any(), z.null()]).describe("Gap at the base (cm)").default(null), "context": z.enum(["balkon","loggia","stiege","fenster","dachterrasse"]).describe("Railing location"), "fall_height": z.any().describe("Absturzhöhe (m) — decides which height limit applies"), "has_horizontal_elements_in_climb_zone": z.union([z.boolean(), z.null()]).describe("Climbable horizontals?").default(null), "max_opening": z.any().describe("Largest opening (cm) vs the <=12 cm cube rule"), "note": z.union([z.string(), z.null()]).describe("Optional clarification").default(null), "rail_height": z.any().describe("Geländerhöhe (cm) vs the required minimum"), "reference": z.any().describe("Source of the guardrail limits (OIB 4)"), "title": z.string().min(1).describe("Title, e.g. 'Absturzsicherung Dachterrasse'"), "type": z.literal("guardrail_check") }).describe("An Absturzsicherung (guardrail) elevation with the interacting limits.\n\nEmit for guardrail/railing questions (OIB 4). Draws the railing to scale and\nchecks height (>=100 cm, >=110 cm where Absturzhöhe > 12 m), max opening\n(<=12 cm cube), bottom gap, and shades the no-climb zone.")

export const densityCheckCardSchema = z.object({ "coverage": z.any().describe("Bebauungsgrad (built/parcel) vs limit; value null = renderer derives"), "density": z.any().describe("GFZ (BGF/parcel) vs limit; null value = renderer derives"), "footprint_area_m2": z.union([z.number(), z.null()]).describe("Built (bebaute) area in m²").default(null), "gross_floor_area_m2": z.union([z.number(), z.null()]).describe("Bruttogeschossfläche (BGF) in m²").default(null), "note": z.union([z.string(), z.null()]).describe("Optional clarification").default(null), "parcel_area_m2": z.number().gt(0).describe("Parcel (Grundstück) area in m²"), "reference": z.any().describe("Source of the limits (usually the Bebauungsplan)"), "title": z.string().min(1).describe("Title, e.g. 'Bebauungsdichte – Grundstück'"), "type": z.literal("density_check") }).describe("A site-density schematic: parcel + footprint + coverage/density bars.\n\nEmit for Bebauungsdichte/Bebauungsgrad/GFZ questions. Draws the parcel with\nthe footprint shaded and two limit bars (built area / parcel and BGF /\nparcel) vs the Bebauungsplan limits. The renderer computes the ratios — the\nmodel supplies areas + the limits (from the user's Bebauungsplan) only.")

export const fireAccessPlanCardSchema = z.object({ "aufstellflaeche": z.any().describe("The fire-brigade standing-area geometry"), "building_depth_m": z.number().gt(0).describe("Building footprint depth in metres"), "building_width_m": z.number().gt(0).describe("Building footprint width in metres"), "gate_clearance_height": z.union([z.any(), z.null()]).describe("Durchfahrt clear height (m)").default(null), "gebaeudeklasse": z.union([z.string(), z.null()]).describe("The building's Gebäudeklasse (drives the limit)").default(null), "note": z.union([z.string(), z.null()]).describe("Optional clarification").default(null), "parcel_depth_m": z.number().gt(0).describe("Parcel depth in metres"), "parcel_width_m": z.number().gt(0).describe("Parcel width in metres"), "reference": z.any().describe("Source of the access requirements (OIB 2 / TRVB)"), "route_width": z.any().describe("Zufahrt clear width (m) vs the minimum"), "title": z.string().min(1).describe("Title, e.g. 'Feuerwehrzufahrt & Aufstellfläche'"), "type": z.literal("fire_access_plan"), "walk_distance_to_entrance": z.any().describe("Reach to farthest entrance (m), e.g. <=80") }).describe("A fire-brigade access (Feuerwehrzufahrt) site plan schematic.\n\nEmit for fire-access questions (OIB 2 / TRVB). Top-down plan: access route\nfrom the road, the Aufstellfläche beside the facade, and the reach distance\nfrom the Aufstellfläche to the farthest necessary entrance (typically\n<=80 m). Numeric minimums vary by Land — always corpus-grounded per check.")

export const acousticCheckCardSchema = z.object({ "checks": z.array(z.any()).describe("The individual dB checks"), "note": z.union([z.string(), z.null()]).describe("Optional clarification").default(null), "sound_class": z.union([z.string(), z.null()]).describe("ÖNORM B 8115-2 Schallschutzklasse, if given").default(null), "title": z.string().min(1).describe("Title, e.g. 'Schallschutz – Wohnungstrennung'"), "type": z.literal("acoustic_check") }).describe("Sound-insulation (Schallschutz) gauges — direction-aware dB checks.\n\nEmit for Schallschutz questions (OIB 5). One gauge per building-part pair:\nairborne (DnTw, higher is better) and impact (LnTw, lower is better) shown\nwith opposite orientation so the margin is unmistakable. Measured values\ncome from the Bauphysik report; unknown → needs_input.")

export const fireCompartmentCardSchema = z.object({ "compartments": z.array(z.any()).describe("The compartments on this level, left-to-right"), "gebaeudeklasse": z.union([z.string(), z.null()]).describe("Gebäudeklasse driving the area limit").default(null), "note": z.union([z.string(), z.null()]).describe("Optional clarification").default(null), "reference": z.any().describe("Source of the max Brandabschnittsfläche (OIB 2)"), "storey_label": z.union([z.string(), z.null()]).describe("Which level the plan shows, e.g. '2.OG'").default(null), "title": z.string().min(1).describe("Title, e.g. 'Brandabschnitte – Regelgeschoss'"), "type": z.literal("fire_compartment") }).describe("A fire-compartment (Brandabschnitt) plan: a storey split into compartments.\n\nEmit for Brandabschnitt questions (OIB 2): draws the storey outline divided\ninto compartments (width proportional to area) separated by Brandwände, each\nread against the maximum permitted Brandabschnittsfläche for its use and\nGebäudeklasse. The limit varies by use/GK — always corpus-grounded.")

export const thermalEnvelopeCardSchema = z.object({ "components": z.array(z.any()).describe("The envelope components to check"), "note": z.union([z.string(), z.null()]).describe("Optional clarification").default(null), "reference": z.any().describe("Source of the max U-values (OIB 6 / ÖNORM B 8110-1)"), "title": z.string().min(1).describe("Title, e.g. 'Wärmeschutz – U-Werte der Gebäudehülle'"), "type": z.literal("thermal_envelope") }).describe("A thermal-envelope (Wärmeschutz) schematic: U-values per building part.\n\nEmit for U-Wert / Wärmeschutz questions (OIB 6). Draws a simple building\ncross-section with each envelope component highlighted by status, and one\nlimit bar per component reading its U-value against the maximum permitted\n(lower is better). Fills the OIB 6 energy-efficiency domain.")

export const energyPerformanceCardSchema = z.object({ "energy_class": z.union([z.string(), z.null()]).describe("Energieeffizienzklasse, e.g. 'A', 'B', 'C'").default(null), "fgee": z.union([z.any(), z.null()]).describe("Gesamtenergieeffizienzfaktor vs its limit").default(null), "hwb": z.any().describe("Heizwärmebedarf kWh/(m²a) vs the max (lower is better, '<=')"), "note": z.union([z.string(), z.null()]).describe("Optional clarification").default(null), "reference": z.any().describe("Source of the HWB requirement (OIB 6)"), "title": z.string().min(1).describe("Title, e.g. 'Energieausweis – Heizwärmebedarf'"), "type": z.literal("energy_performance") }).describe("An energy-performance (Energieausweis) card: HWB on the A–G class ladder.\n\nEmit for Energieausweis / Heizwärmebedarf questions (OIB 6). Draws the\nA++…G energy-class ladder with the building's class highlighted, and reads\nthe Heizwärmebedarf (kWh/m²a) against the required maximum. fGEE optional.")

export const elevatorRequirementCardSchema = z.object({ "cabin_depth": z.union([z.any(), z.null()]).describe("Kabinentiefe (cm) vs the minimum (>=140)").default(null), "cabin_width": z.union([z.any(), z.null()]).describe("Kabinenbreite (cm) vs the minimum (>=110)").default(null), "door_width": z.union([z.any(), z.null()]).describe("lichte Türbreite (cm) vs the minimum (>=90)").default(null), "entrance_level_index": z.union([z.number().int(), z.null()]).describe("0-based index of the entrance level").default(null), "is_required": z.union([z.boolean(), z.null()]).describe("Is a barrier-free lift required? null = unknown").default(null), "note": z.union([z.string(), z.null()]).describe("Optional clarification").default(null), "reference": z.any().describe("Source of the lift requirement (OIB 4 / ÖNORM B 1600)"), "requirement_note": z.union([z.string(), z.null()]).describe("Why a lift is / isn't required").default(null), "storeys_served": z.number().int().gt(0).describe("Number of levels the building has (drawn as a stack)"), "title": z.string().min(1).describe("Title, e.g. 'Barrierefreier Aufzug – Erschließung'"), "type": z.literal("elevator_requirement") }).describe("A barrier-free-elevator (Aufzug) card: requirement + cabin dimensions.\n\nEmit for Aufzug / barrierefreie-Erschließung questions (OIB 4). Draws the\nserved storeys as a stack with a lift shaft, states whether a barrier-free\nlift is required (drives from storey count / arrival level), and checks the\ncabin and door clear dimensions against the accessibility minimums.")

export const parkingRequirementCardSchema = z.object({ "basis": z.union([z.string(), z.null()]).describe("How the requirement is derived, e.g. '1 Stpl. je 100 m² BGF'").default(null), "bicycle_spaces": z.union([z.any(), z.null()]).describe("Provided vs required Fahrradabstellplätze").default(null), "car_spaces": z.any().describe("Provided vs required Kfz-Stellplätze (comparator '>=')"), "note": z.union([z.string(), z.null()]).describe("Optional clarification").default(null), "reference": z.any().describe("Source of the parking requirement (Bauordnung / StPl-VO)"), "title": z.string().min(1).describe("Title, e.g. 'Stellplatznachweis – Wohnbau'"), "type": z.literal("parking_requirement") }).describe("A parking-provision (Stellplatznachweis) card: required vs provided count.\n\nEmit for Stellplatz / Fahrradabstellplatz questions (Bauordnung /\nStellplatzverordnung). Draws a slot grid — outline slots for the required\ncount, filled for those provided — and reads provided against the required\nminimum for cars and, optionally, bicycles.")

export const memoryProposalCardSchema = z.object({ "confidence": z.enum(["low","medium","high"]).default("medium"), "content": z.string().min(1).describe("The finding to remember (shown to the user verbatim)"), "kind": z.enum(["decision","constraint","open_question","derived_fact","preference"]), "title": z.string().min(1).describe("Short title for the memory proposal"), "type": z.literal("memory_proposal") }).describe("A proposal to save a finding to long-term memory, confirmed by the user.\n\nSystem-emitted by the `remember` tool when an org-scoped write needs human\nauthorization; the user chooses org-wide or project scope and the write goes\nthrough their authenticated session.")

export const acousticCheckItemSchema = z.object({ "check": z.any().describe("Measured vs required in dB (comparator differs by metric)"), "metric": z.enum(["DnTw","LnTw","Rw_res"]).describe("Airborne / impact / resulting metric"), "path_label": z.string().min(1).describe("What is separated, e.g. 'Wohnungstrennwand Top 3/Top 4'"), "reference": z.any().describe("Source of the dB limit (OIB 5 / ÖNORM B 8115-2)") }).describe("One sound-insulation check between two building parts.")

export const aufstellflaechePlanSchema = z.object({ "distance_to_facade": z.union([z.any(), z.null()]).describe("Distance to the facade (m)").default(null), "length": z.any().describe("Aufstellfläche length (m)"), "width": z.any().describe("Aufstellfläche width (m)") }).describe("The fire-brigade Aufstellfläche geometry.")

export const checklistItemSchema = z.object({ "detail": z.union([z.string(), z.null()]).describe("Short explanation or the relevant measured value").default(null), "label": z.string().min(1).describe("The requirement, e.g. 'Zweiter Fluchtweg vorhanden'"), "reference": z.union([z.any(), z.null()]).describe("Where this requirement comes from").default(null), "status": z.enum(["pass","fail","warning","needs_input"]).describe("Verdict for this requirement") }).describe("One requirement in a checklist, with its verdict and grounding.")

export const comparisonRowSchema = z.object({ "highlight_index": z.union([z.number().int().gte(0), z.null()]).describe("0-based index of the option favoured on this criterion, if any").default(null), "label": z.string().min(1).describe("Criterion, e.g. 'max. Brandabschnittsfläche'"), "values": z.array(z.string()).min(1).describe("One value per option, same order as `options`") }).describe("One criterion compared across the options (one value per option).")

export const dimensionCheckSchema = z.object({ "comparator": z.union([z.enum(["<=",">="]), z.null()]).describe("How actual must relate to required").default(null), "label": z.string().min(1).describe("What is measured, e.g. 'lichte Durchgangsbreite'"), "required": z.union([z.number(), z.null()]).describe("OIB limit for this dimension").default(null), "status": z.enum(["pass","fail","warning","needs_input"]).describe("Verdict for this dimension"), "unit": z.string().describe("Unit for both value and required, e.g. 'cm', 'm', '%'").default("cm"), "value": z.union([z.number(), z.null()]).describe("Actual measurement (drawn); null if unknown").default(null) }).describe("One measured dimension drawn on a schematic and checked against a limit.\n\n`value` is the project's actual measurement (drawn to scale); `required` is\nthe OIB limit. If `value` is unknown, leave it null and set status\n'needs_input'.")

export const egressSegmentSchema = z.object({ "label": z.string().min(1).describe("Segment label, e.g. 'Raum → Gang', 'Gang → Treppenhaus'"), "length_m": z.number().gt(0).describe("Run length in metres (drawn to scale)"), "turn": z.enum(["straight","left","right"]).describe("Turn AFTER this run").default("straight") }).describe("One straight run of an escape path, drawn end-to-end with the next.")

export const envelopeComponentSchema = z.object({ "kind": z.enum(["wall","roof","floor","window","door"]).describe("Where it sits in the section"), "label": z.string().min(1).describe("Component, e.g. 'Außenwand', 'Dach', 'Fenster'"), "u_value": z.any().describe("U-Wert W/(m²K) vs the max U-value (lower is better, '<=')") }).describe("One thermal-envelope component with its U-value checked against a limit.")

export const fireCompartmentSchema = z.object({ "area": z.any().describe("Brandabschnittsfläche (m²) vs the max permitted (comparator '<=')"), "label": z.string().min(1).describe("Compartment name, e.g. 'BA 1 – Wohnungen OG'"), "use": z.union([z.string(), z.null()]).describe("Nutzung, e.g. 'Wohnen', 'Büro', 'Tiefgarage'").default(null) }).describe("One Brandabschnitt (fire compartment) drawn as a band, area-checked.")

export const normReferenceSchema = z.object({ "binding": z.union([z.string(), z.null()]).describe("System-stamped binding role: normativ | anwendend | erklaerend").default(null), "document": z.string().min(1).describe("Regulation name, e.g. 'OIB-Richtlinie 2', 'ÖNORM B 1600'"), "edition": z.union([z.string(), z.null()]).describe("Edition/year, e.g. 'Ausgabe Mai 2023'").default(null), "excerpt": z.union([z.string(), z.null()]).describe("Literal quoted sentence grounding the value (<= ~200 chars)").default(null), "norm_id": z.union([z.string(), z.null()]).describe("System-stamped registry id (never authored by the LLM), e.g. 'oib-rl-2'").default(null), "rank": z.union([z.string(), z.null()]).describe("System-stamped registry rank, e.g. 'oib_richtlinie'").default(null), "section": z.union([z.string(), z.null()]).describe("Clause/table, e.g. 'Pkt. 5.1.1', 'Tabelle 1b'").default(null), "via": z.union([z.string(), z.null()]).describe("System-stamped declaring instrument, e.g. 'WBTV'").default(null) }).describe("A verifiable pointer into a regulation (the atom of grounding).\n\nEvery required value MUST carry one so the architect can verify it against\nthe source. Never fabricate a reference.")

export const obstructionSchema = z.object({ "distance_m": z.number().gt(0).describe("Horizontal distance from the window in metres"), "height_m": z.number().describe("Height of the obstruction above the window sill in metres"), "label": z.string().min(1).describe("What it is, e.g. 'Gegenüberliegendes Gebäude'") }).describe("An object blocking daylight (opposing building, own projection).")

export const projectProfilePatchOperationSchema = z.object({ "op": z.enum(["add","replace","remove"]), "path": z.string().describe("For a confirmed hard fact use \"/facts/<key>\" with op \"add\" (works for both new and changed values). For an uncertain inference use \"/assumptions/<key>\". Known fact keys and values: hauptnutzung: wohnen|buero|beherbergung|versammlung|gesundheit|landwirtschaft|produzierend|lager|sonstiges; gebaeudeklasse: GK1|GK2|GK3|GK4|GK5; fluchtniveau: <=7m|7-11m|11-22m|>22m; bestand_neubau: bestand|neubau|zu_und_umbau; widmung: bauland|verkehrsflaeche|freiland|kerngebiet|gemischt; bauweise: offen|gekuppelt|geschlossen; sicherheitskategorie: low|medium|high; bestandsalter: <10|10-30|30-50|>50; geschosse_oberirdisch / geschosse_unterirdisch / anzahl_betten / anzahl_einheiten: number; grundgrenze / fluchtlinie / schutzzone / abweichender_bebauungsplan: boolean; hohe_gebaeude_details: free text"), "value": z.any().describe("The PLAIN value only (e.g. \"GK4\", 3, true) — never wrap it in an object; the app adds provenance metadata when the user accepts.").default(null) }).describe("A JSON Patch operation targeting a project profile section.")

export const projectProfilePatchPreviewItemSchema = z.object({ "after": z.string(), "before": z.string(), "label": z.string() }).describe("A before/after preview for a single patched field.")

export const sectionMarkerSchema = z.object({ "height_m": z.number().describe("Height above ground datum in metres"), "kind": z.enum(["fluchtniveau","threshold","reference"]).describe("Styling role").default("reference"), "label": z.string().min(1).describe("What the line marks, e.g. 'Fluchtniveau', 'GK4-Grenze'") }).describe("A horizontal reference line at a given height in the section.")

export const sectionStoreySchema = z.object({ "below_grade": z.boolean().describe("True for basements/underground storeys").default(false), "height_m": z.number().gt(0).describe("Clear storey height in metres (drawn to scale)"), "label": z.string().min(1).describe("Storey label, e.g. 'EG', '1.OG', 'KG'") }).describe("One storey in a building cross-section, drawn as a band to scale.")

export const setbackSideSchema = z.object({ "actual_m": z.union([z.number(), z.null()]).describe("Actual distance in metres; null if unknown").default(null), "required_m": z.number().describe("Required setback in metres (OIB/Bauordnung)"), "side": z.enum(["front","back","left","right"]).describe("Which edge"), "status": z.enum(["pass","fail","warning","needs_input"]).describe("Verdict for this side") }).describe("A required distance from the building footprint to one parcel edge.")

export const gridCardSchema = z.discriminatedUnion('type', [
  summaryCardSchema,
  legalBasisCardSchema,
  projectProfilePatchCardSchema,
  requirementChecklistCardSchema,
  comparisonTableCardSchema,
  buildingSectionCardSchema,
  stairDiagramCardSchema,
  dimensionDiagramCardSchema,
  setbackPlanCardSchema,
  egressDiagramCardSchema,
  daylightIncidenceCardSchema,
  guardrailCheckCardSchema,
  densityCheckCardSchema,
  fireAccessPlanCardSchema,
  acousticCheckCardSchema,
  fireCompartmentCardSchema,
  thermalEnvelopeCardSchema,
  energyPerformanceCardSchema,
  elevatorRequirementCardSchema,
  parkingRequirementCardSchema,
  memoryProposalCardSchema,
])
