/**
 * Legal documents — English.
 *
 * Structural counterpart of `./de.ts` (German is the authoritative market
 * language for the Austrian product; this translation is provided for
 * convenience). Operator identity fields are deliberate placeholders marked
 * with [BRACKETS] — they MUST be completed before production use.
 *
 * These texts were prepared as part of the 2026-07 compliance review
 * (docs/compliance/) and are templates, not legal advice: have counsel
 * review them before relying on them.
 */

import type { LegalContent } from '../types'

const OPERATOR = '[Operator name — e.g. GRID Check GmbH]'
const ADDRESS = '[Street, number, postal code, city, Austria]'
const EMAIL = '[contact email address]'

export const en: LegalContent = {
  imprint: {
    title: 'Imprint',
    updated: '2026-07-10',
    intro:
      'Information pursuant to §5 E-Commerce-Gesetz (ECG), §25 Mediengesetz and §63 Gewerbeordnung (Austria).',
    sections: [
      {
        heading: 'Operator of this service',
        paragraphs: [
          `${OPERATOR}, ${ADDRESS}.`,
          `Contact: ${EMAIL}`,
          'Company register number: [FN number], Company register court: [court]. VAT ID: [ATU number].',
          'Business purpose: [e.g. IT services / software as a service]. Supervisory authority pursuant to ECG: [competent district administrative authority]. Applicable trade regulations: Gewerbeordnung 1994, available at ris.bka.gv.at.',
        ],
      },
      {
        heading: 'Purpose of the service',
        paragraphs: [
          'Grid is an AI-assisted research tool that helps building professionals find and verify information from the Austrian OIB-Richtlinien and legal sources published in the Rechtsinformationssystem des Bundes (RIS). Grid does not provide legal advice; see the Terms of Use and the AI Transparency notice.',
        ],
      },
      {
        heading: 'Online dispute resolution',
        paragraphs: [
          'Consumers may submit complaints to the EU online dispute resolution platform: https://ec.europa.eu/odr. You can also address complaints to the email address given above.',
        ],
      },
      {
        heading: 'Liability for content',
        paragraphs: [
          'Answers produced by this service are generated by an AI system and may be incorrect or incomplete. They are no substitute for reviewing the applicable regulations or for professional advice. The cited primary sources (OIB-Richtlinien, RIS) prevail in every case.',
        ],
      },
    ],
  },

  privacy: {
    title: 'Privacy Policy',
    updated: '2026-07-10',
    intro:
      'This policy explains how personal data is processed when you use Grid, pursuant to Regulation (EU) 2016/679 (GDPR / DSGVO).',
    sections: [
      {
        heading: '1. Controller',
        paragraphs: [
          `Controller within the meaning of Art. 4(7) GDPR: ${OPERATOR}, ${ADDRESS}, ${EMAIL}.`,
          'Where Grid is provided to you through your employer or organization, that organization determines the purposes of processing project content within its workspace; in that respect the operator acts as processor on the organization’s behalf and a data processing agreement (Art. 28 GDPR) governs the relationship.',
        ],
      },
      {
        heading: '2. What data we process',
        list: [
          'Account and organization data: name, email address, organization membership, roles and permissions. Identity is managed by our identity provider WorkOS (AuthKit); we deliberately keep no separate local copy of your identity profile.',
          'Content data: your chat questions and the answers generated for you, research reports, project documents you upload (plans, permits, specifications — which may themselves contain personal data), and project/organization memory entries derived from your interactions.',
          'Usage and billing data: a usage ledger recording, per AI request, the requested and actually serving AI model, token counts and cost, attributed to your organization, project and user.',
          'Audit data: privileged administrative actions (e.g. model configuration changes, budget changes, deletions, legal holds) are recorded with actor, timestamp, IP address and user agent.',
          'Technical data: server logs, session cookie (authentication), locale preference cookie.',
        ],
      },
      {
        heading: '3. Purposes and legal bases (Art. 6 GDPR)',
        list: [
          'Providing the service, answering your questions, storing your projects — Art. 6(1)(b) (performance of contract).',
          'Security, access control, audit trails, abuse prevention (rate limits, admission control) — Art. 6(1)(f) (legitimate interest in secure, accountable operation).',
          'Usage metering and budget enforcement — Art. 6(1)(b) and (f).',
          'Compliance with legal obligations (e.g. retention under legal hold, accounting) — Art. 6(1)(c).',
        ],
      },
      {
        heading: '4. AI processing and recipients of your content',
        paragraphs: [
          'To generate answers, your chat messages, relevant excerpts of your uploaded documents and retrieved regulation passages are transmitted to external AI model providers via the API gateway OpenRouter, Inc. (USA). Web-research queries derived from your questions are sent to the search provider Tavily. Identity and sign-in are handled by WorkOS, Inc. (USA).',
        ],
        notice:
          'Important: which AI model — and therefore which upstream model provider (e.g. DeepSeek, OpenAI, Anthropic, Google, Meta, Mistral and others listed in the OpenRouter catalog) — processes your requests is configurable at runtime by your organization’s administrators. All AI traffic always flows through OpenRouter and never through any other gateway, but the effective downstream provider, and thus the location of that processing (which may be outside the EU/EEA), depends on the model your organization selects. Every model change is validated, versioned, attributable to the administrator who made it, and auditable; the model that actually served each request is recorded. The current list of external services is available on the Subprocessors page.',
      },
      {
        heading: '5. International transfers (Art. 44 ff GDPR)',
        paragraphs: [
          'Several service providers are located in the United States or other third countries, and the upstream AI model selected by your organization may be hosted outside the EU/EEA. Transfers are based on adequacy decisions (including the EU-US Data Privacy Framework, where the provider is certified) and/or standard contractual clauses. Details per provider are listed on the Subprocessors page. Your organization’s administrators can restrict the selectable models.',
        ],
      },
      {
        heading: '6. Storage, retention and deletion',
        paragraphs: [
          'Project content is stored in our application database, in object storage (uploaded documents) and in a vector index (document embeddings) — all operated within our own infrastructure. When a project is deleted it is first soft-deleted and restorable during a grace period, after which an automated purge permanently removes it from all stores (database, object storage, vector index, and the associated authorization records). Deletion can be suspended by a legal hold (Art. 18 GDPR restriction) placed by your organization’s compliance role; every hold and release is recorded in the audit trail.',
          'Usage-ledger and audit records are retained for accountability and billing purposes for as long as the organization’s contract and statutory retention periods require.',
        ],
      },
      {
        heading: '7. Cookies',
        paragraphs: [
          'Grid uses only strictly necessary cookies: an encrypted session cookie for sign-in (WorkOS AuthKit) and a cookie storing your language preference. No advertising or cross-site tracking cookies are set. Because only strictly necessary cookies are used, no cookie consent banner is required (§165 TKG 2021).',
        ],
      },
      {
        heading: '8. Your rights',
        paragraphs: [
          'You have the right to access (Art. 15), rectification (Art. 16), erasure (Art. 17), restriction (Art. 18), data portability (Art. 20) and objection (Art. 21). Where processing is based on consent you may withdraw it at any time. If Grid is provided through your organization, please direct requests to your organization first; we support the organization in fulfilling them.',
          `To exercise your rights, contact ${EMAIL}. You also have the right to lodge a complaint with the Austrian Data Protection Authority (Datenschutzbehörde), Barichgasse 40–42, 1030 Vienna, dsb.gv.at, or your local supervisory authority.`,
        ],
      },
      {
        heading: '9. Data security (Art. 32 GDPR)',
        paragraphs: [
          'Access is protected by single sign-on with optional multi-factor authentication, role-based permissions and tenant isolation enforced on every request. Administrative actions are audit-logged. Transport encryption (TLS) protects data in transit. Internal service-to-service calls are authenticated with dedicated tokens.',
        ],
      },
      {
        heading: '10. Changes',
        paragraphs: [
          'We will update this policy when the service or its providers change and will indicate the date of the last revision above. Material changes affecting organizations will be announced to organization administrators.',
        ],
      },
    ],
  },

  terms: {
    title: 'Terms of Use',
    updated: '2026-07-10',
    intro:
      'These terms govern the use of Grid. Template — to be reviewed and completed by counsel before production use.',
    sections: [
      {
        heading: '1. Scope of service',
        paragraphs: [
          'Grid is an AI-assisted research assistant for Austrian building regulations (OIB-Richtlinien and RIS legal sources). It retrieves, summarizes and cites regulatory content and project documents provided by your organization.',
        ],
      },
      {
        heading: '2. No legal advice',
        paragraphs: [
          'Grid does not provide legal advice (keine Rechtsberatung) and does not replace the judgement of qualified professionals such as architects, civil engineers or lawyers. Answers are AI-generated, may be incorrect, incomplete or outdated, and must be verified against the cited primary sources before being relied on for planning, permitting or construction decisions. Responsibility for decisions based on Grid output remains with the user and their organization.',
        ],
      },
      {
        heading: '3. Accounts and organizations',
        paragraphs: [
          'Access requires an account within an organization. Organization administrators manage membership, roles, projects, budgets and the AI model configuration for their organization and are responsible for those choices.',
        ],
      },
      {
        heading: '4. AI model selection',
        paragraphs: [
          'Organization administrators may select the AI models used by their organization from the validated catalog at runtime. The operator routes all AI traffic through its configured gateway (OpenRouter) and never lets a model change alter the gateway or credentials, but the selected upstream model provider processes organization content as described in the Privacy Policy and AI Transparency notice. The organization is responsible for its model selection, including any data-location consequences; every change is recorded and reversible.',
        ],
      },
      {
        heading: '5. Acceptable use',
        list: [
          'No unlawful content, no infringement of third-party rights in uploaded documents.',
          'No attempts to circumvent tenant isolation, authentication, rate limits or usage budgets.',
          'No use of the service to generate content that violates applicable law.',
          'Uploaded documents must be limited to material the organization is entitled to process.',
        ],
      },
      {
        heading: '6. Availability and support',
        paragraphs: [
          'The service is provided without a guaranteed service level unless agreed otherwise in writing. Planned maintenance and dependencies on external providers (identity, AI models, web search) can affect availability. [Insert agreed SLA / support terms if applicable.]',
        ],
      },
      {
        heading: '7. Data and deletion',
        paragraphs: [
          'Organizations retain ownership of their content. Deleted projects are restorable during a grace period and then permanently purged from all stores, unless a legal hold applies. Details in the Privacy Policy.',
        ],
      },
      {
        heading: '8. Liability',
        paragraphs: [
          'Liability for slight negligence is excluded to the extent permitted by law; mandatory liability (e.g. for personal injury, under the Produkthaftungsgesetz) remains unaffected. The operator is not liable for decisions made in reliance on AI-generated output contrary to Section 2. [Complete limitation-of-liability clause with counsel.]',
        ],
      },
      {
        heading: '9. Final provisions',
        paragraphs: [
          'Austrian law applies, excluding its conflict-of-law rules and the UN Sales Convention. Place of jurisdiction: [competent court], for consumers subject to mandatory consumer-protection venues. Should individual provisions be invalid, the remainder stays in force.',
        ],
      },
    ],
  },

  'ai-transparency': {
    title: 'AI Transparency Notice',
    updated: '2026-07-10',
    intro:
      'Information pursuant to Art. 50 of Regulation (EU) 2024/1689 (AI Act) about the AI system you interact with when using Grid.',
    sections: [
      {
        heading: 'You are interacting with an AI system',
        paragraphs: [
          'Grid answers your questions using large language models (LLMs). Chat answers, research reports and legal-basis cards are AI-generated content. Grid marks the sources it cites so every statement can be verified against the OIB-Richtlinie or RIS provision it is based on.',
        ],
      },
      {
        heading: 'What the system does',
        paragraphs: [
          'Grid retrieves passages from the OIB-Richtlinien, Austrian legal sources (RIS) and your project documents, optionally performs web research, and uses AI models to compose an answer with citations. An asynchronous memory function can derive project- and organization-level notes from interactions to improve future answers; organization-wide memory writing by the AI is disabled by default.',
        ],
      },
      {
        heading: 'Limits and human oversight',
        paragraphs: [
          'AI-generated answers can be wrong, incomplete or outdated even when they sound confident. Grid is a research aid, classified as a limited-risk AI application: it does not make decisions about buildings, permits or persons — professional review of every answer against the cited primary source is a required part of its intended use. Do not use Grid output as the sole basis for safety-relevant planning decisions.',
        ],
      },
      {
        heading: 'Which AI models are used',
        paragraphs: [
          'By default, Grid uses models routed through the API gateway OpenRouter (reference model: DeepSeek). Different internal functions (intent detection, clarification, research, deep research, memory reflection) may use different models.',
        ],
        notice:
          'Model choice is dynamic: administrators of your organization can re-point each function to a different AI model from the OpenRouter catalog at any time, without a new release of the service. Every change is validated against the catalog, versioned, attributed to the administrator who made it and reversible, and for every single AI request the model that actually produced the answer is recorded in the usage ledger. The gateway (OpenRouter) and its credentials can never be changed by a model selection — only which model behind that gateway serves your organization.',
      },
      {
        heading: 'Traceability',
        paragraphs: [
          'For each answer, Grid records which model served the request, the tokens consumed and the cost, attributed to organization, project and user. Administrative changes to the model configuration appear in the organization audit log.',
        ],
      },
      {
        heading: 'Questions',
        paragraphs: [
          `For questions about the AI system, its models or this notice, contact ${EMAIL}.`,
        ],
      },
    ],
  },

  subprocessors: {
    title: 'External Services & Subprocessors',
    updated: '2026-07-10',
    intro:
      'All external services that can process data when you use Grid, and the infrastructure the operator runs itself. This page implements the transparency commitment referenced in the Privacy Policy.',
    sections: [
      {
        heading: 'External processors',
        table: {
          headers: ['Service', 'Purpose', 'Data processed', 'Location', 'Required?'],
          rows: [
            [
              'WorkOS, Inc.',
              'Identity & sign-in (SSO, MFA), authorization, audit-log storage',
              'Name, email, organization membership, roles, sign-in events, audit events (incl. IP address)',
              'USA',
              'Yes',
            ],
            [
              'OpenRouter, Inc.',
              'AI gateway for all language-model, embedding and vision-model requests',
              'Chat messages, document excerpts, retrieved regulation passages, generated answers',
              'USA (gateway); upstream model provider varies — see notice below',
              'Yes',
            ],
            [
              'Upstream AI model providers (via OpenRouter, e.g. DeepSeek, OpenAI, Anthropic, Google, Meta, Mistral)',
              'Operating the AI model selected by your organization',
              'Same content as OpenRouter receives',
              'Depends on selected model (may be outside EU/EEA)',
              'One at a time, selected per organization',
            ],
            [
              'Tavily',
              'Web search for research questions',
              'Search queries derived from your questions (AI-generated from your prompts)',
              'USA',
              'Yes (for web research)',
            ],
            [
              'Additional search providers (Exa, Serper/Google Scholar, DuckDuckGo, Polymarket)',
              'Alternative/optional search tools',
              'Search queries derived from your questions',
              'USA / various',
              'Optional (only if configured)',
            ],
            [
              'Modal Labs',
              'Sandboxed code execution during deep research',
              'Code and data the research agent chooses to execute',
              'USA',
              'Optional (only if configured)',
            ],
            [
              'NVIDIA (integrate.api.nvidia.com)',
              'Embeddings and vision/table extraction from documents (default configuration; the production reference setup routes these through OpenRouter instead)',
              'Document text chunks and page images',
              'USA',
              'Depends on deployment configuration',
            ],
            [
              'Moonshot AI (Kimi)',
              'Alternative AI model configuration',
              'Chat messages and document excerpts',
              'China',
              'Optional (non-default configuration)',
            ],
            [
              'Hosting provider',
              'Runs the application, databases and object storage',
              'All application data',
              '[Complete: provider & region]',
              'Yes',
            ],
          ],
        },
        notice:
          'Dynamic model providers: because organization administrators can switch the AI model at runtime (see the AI Transparency notice), the effective upstream model provider is not fixed. All AI traffic always passes through OpenRouter; the set of possible upstream providers is limited to the OpenRouter catalog; the selection active for your organization is visible to your administrators, every change is audited, and the serving model is recorded per request.',
      },
      {
        heading: 'Self-hosted infrastructure (no third-party processing)',
        table: {
          headers: ['Component', 'Purpose', 'Data held'],
          rows: [
            ['PostgreSQL', 'Application database', 'Projects, conversations, memory, usage ledger, configuration'],
            ['MinIO (S3-compatible)', 'Object storage', 'Uploaded documents'],
            ['ChromaDB', 'Vector index', 'Document and regulation embeddings'],
            ['Dragonfly (Redis-compatible)', 'Cache, rate limiting', 'Short-lived operational data'],
          ],
        },
      },
      {
        heading: 'Optional telemetry (disabled by default)',
        paragraphs: [
          'The codebase supports optional tracing/monitoring integrations (Datadog RUM, LangSmith, Weights & Biases) which are inactive unless explicitly configured by the operator. If enabled for a deployment, this page will be updated accordingly.',
        ],
      },
      {
        heading: 'Changes to this list',
        paragraphs: [
          'The operator will update this page before engaging new subprocessors that process organization content. Organization administrators will be informed of material changes.',
        ],
      },
    ],
  },
}
