import * as k8s from "@pulumi/kubernetes";
import * as pulumi from "@pulumi/pulumi";
// Strongly-typed CRD resource classes generated by crd2pulumi from the EXACT
// deployed CRDs (Gateway API v1.5.1 + Envoy Gateway v1.2.4's successor v1.8.0),
// vendored under ./crds. Unlike an untyped `apiextensions.CustomResource`, these
// classes fix apiVersion/kind and type `metadata` + `spec` field-by-field
// against the real schema — a bad field fails `tsc`, not `pulumi up`. Regenerate
// with `npm run gen:crds` after bumping a CRD version.
import * as crds from "../../crds";
import { GridConfig } from "../config";
import { commonLabels } from "./namespaces";

/** Stable names referenced by the cert-manager solver and the HTTPRoutes. */
export const GATEWAY_NAME = "grid-gateway";
export const GATEWAY_CLASS = "eg";

/**
 * Edge on the **Gateway API** (not the legacy Ingress API, and not the retired
 * ingress-nginx). Implementation: **Envoy Gateway** (CNCF, Gateway-API native).
 *
 * Pinned to a supported release (v1.2.x/v1.6.x are EOL). The `gateway-helm`
 * chart still installs both the Gateway API standard-channel CRDs and the Envoy
 * Gateway CRDs by default (`crds.enabled=true`).
 *
 * Ordering: the controller ships the CRDs, which cert-manager must see at
 * startup to enable its Gateway integration — so install the controller FIRST,
 * then cert-manager, then the Gateway/GatewayClass resources.
 */
const ENVOY_GATEWAY_VERSION = "v1.8.0";

export function installGatewayController(provider: k8s.Provider): k8s.helm.v3.Release {
  const ns = new k8s.core.v1.Namespace(
    "envoy-gateway-ns",
    { metadata: { name: "envoy-gateway-system" } },
    { provider },
  );

  return new k8s.helm.v3.Release(
    "envoy-gateway",
    {
      chart: "oci://docker.io/envoyproxy/gateway-helm",
      version: ENVOY_GATEWAY_VERSION,
      namespace: ns.metadata.name,
      // Install CRDs + controller with the chart's defaults. DO NOT override
      // `values.crds` or set `skipAwait`: cert-manager (installed next with
      // enableGatewayAPI) hard-fails at startup if the Gateway API CRDs aren't
      // Established first, and the default release-await guarantees that order.
      values: {},
    },
    { provider, dependsOn: ns },
  );
}

/**
 * GatewayClass `eg` (bound to the Envoy Gateway controller) + the Gateway with
 * an HTTP :80 listener (ACME HTTP-01 challenge) and per-host HTTPS :443
 * listeners for appDomain + s3Domain. TLS is provisioned by cert-manager's
 * Gateway shim: the annotation names the ClusterIssuer, and cert-manager
 * creates a Certificate for each listener's `certificateRefs` secret.
 */
export function installGatewayResources(
  cfg: GridConfig,
  provider: k8s.Provider,
  namespace: pulumi.Input<string>,
  issuerName: pulumi.Input<string>,
  dependsOn: pulumi.Resource[],
): { gatewayClass: crds.gateway.v1.GatewayClass; gateway: crds.gateway.v1.Gateway } {
  const gatewayClass = new crds.gateway.v1.GatewayClass(
    "grid-gatewayclass",
    {
      metadata: { name: GATEWAY_CLASS, labels: commonLabels("gateway") },
      spec: { controllerName: "gateway.envoyproxy.io/gatewayclass-controller" },
    },
    { provider, dependsOn },
  );

  // Managed-proxy infrastructure: Envoy Gateway defaults the generated Envoy
  // fleet to a SINGLE replica with no PDB — the whole cluster's front door
  // would ride on one pod on one node (a node drain = full outage for both
  // domains). Pin 2 replicas, a PDB, and spread them across nodes.
  const envoyProxyConfig = new crds.gateway.v1alpha1.EnvoyProxy(
    "grid-envoy-proxy-config",
    {
      metadata: { name: "grid-envoy-proxy", namespace, labels: commonLabels("gateway") },
      spec: {
        provider: {
          type: "Kubernetes",
          kubernetes: {
            envoyDeployment: {
              replicas: 2,
              pod: {
                affinity: {
                  podAntiAffinity: {
                    preferredDuringSchedulingIgnoredDuringExecution: [
                      {
                        weight: 100,
                        podAffinityTerm: {
                          topologyKey: "kubernetes.io/hostname",
                          labelSelector: {
                            matchLabels: {
                              "gateway.envoyproxy.io/owning-gateway-name": GATEWAY_NAME,
                            },
                          },
                        },
                      },
                    ],
                  },
                },
              },
            },
            envoyPDB: { minAvailable: 1 },
          },
        },
      },
    },
    { provider, dependsOn },
  );

  const gateway = new crds.gateway.v1.Gateway(
    "grid-gateway",
    {
      metadata: {
        name: GATEWAY_NAME,
        namespace,
        labels: commonLabels("gateway"),
        annotations: { "cert-manager.io/cluster-issuer": issuerName },
      },
      spec: {
        gatewayClassName: GATEWAY_CLASS,
        // Attach the HA proxy-infrastructure config above.
        infrastructure: {
          parametersRef: {
            group: "gateway.envoyproxy.io",
            kind: "EnvoyProxy",
            name: "grid-envoy-proxy",
          },
        },
        listeners: [
          {
            // Open for the ACME HTTP-01 challenge (cert-manager attaches a
            // temporary HTTPRoute here).
            name: "http",
            port: 80,
            protocol: "HTTP",
            allowedRoutes: { namespaces: { from: "Same" } },
          },
          {
            name: "https-app",
            port: 443,
            protocol: "HTTPS",
            hostname: cfg.ingress.appDomain,
            tls: { mode: "Terminate", certificateRefs: [{ name: "grid-app-tls" }] },
            allowedRoutes: { namespaces: { from: "Same" } },
          },
          {
            name: "https-s3",
            port: 443,
            protocol: "HTTPS",
            hostname: cfg.ingress.s3Domain,
            tls: { mode: "Terminate", certificateRefs: [{ name: "grid-s3-tls" }] },
            allowedRoutes: { namespaces: { from: "Same" } },
          },
        ],
      },
    },
    { provider, dependsOn: [gatewayClass, envoyProxyConfig] },
  );

  // Long-lived WebSocket chat upgrades. `streamIdleTimeout` is the per-stream
  // idle timer that actually governs an open-but-idle WS (Envoy default ~5min),
  // the one that would otherwise sever a quiet chat mid-session; `idleTimeout`
  // is the connection-level timer and never fires while a stream is active, but
  // keep it raised too for consistency.
  new crds.gateway.v1alpha1.ClientTrafficPolicy(
    "grid-client-traffic-policy",
    {
      metadata: { name: "grid-ws-timeouts", namespace, labels: commonLabels("gateway") },
      spec: {
        targetRefs: [{ group: "gateway.networking.k8s.io", kind: "Gateway", name: GATEWAY_NAME }],
        timeout: { http: { idleTimeout: "3600s", streamIdleTimeout: "3600s" } },
      },
    },
    { provider, dependsOn: gateway },
  );

  return { gatewayClass, gateway };
}
