import { eq } from 'drizzle-orm'
import { getDb } from '@/lib/db'
import { projects } from '@/lib/db/schema'
import { getCached, invalidateCached } from '@/lib/cache'
import { buildProjectBriefView } from './brief-view'
import { isValidBundeslandToken } from './intake-definition'
import { ProjectProfileSchema } from './types'
import type { ProjectPrimitiveValue, ProjectProfile, ProjectProfileDisplay } from './types'

// Re-exported so existing server-side importers (profile / patches routes, tests)
// keep a single import surface; the engine itself now lives in the isomorphic
// patch-engine module so the intake wizard can share it.
export { applyProjectProfilePatch, emptyProjectProfile } from './patch-engine'

const PROMPT_VIEW_CACHE_TTL_MS = 5 * 60 * 1000

/**
 * Cached read of the project-context prompt view injected into the agent on
 * every WS upgrade. Backed by the shared cache (ADR-0020), so a profile edit
 * on one replica invalidates for all replicas — the per-process Map this
 * replaces served stale project context for up to 5 minutes after an edit.
 */
export async function loadProjectPromptView(projectId: string | undefined): Promise<string | null> {
  if (!projectId) return null

  return getCached(`promptview:${projectId}`, PROMPT_VIEW_CACHE_TTL_MS, async () => {
    const db = getDb()
    const [project] = await db
      .select({ profilePromptView: projects.profilePromptView })
      .from(projects)
      .where(eq(projects.id, projectId))
      .limit(1)
    const promptView = project?.profilePromptView?.trim()
    return promptView || null
  })
}

export async function invalidateProjectPromptViewCache(projectId: string): Promise<void> {
  await invalidateCached(`promptview:${projectId}`)
}

/**
 * Cached read of the project's validated `bundesland` fact, straight off the
 * stored structured profile (`projects.profile.facts.bundesland.value`) —
 * the SAME source `buildProjectPromptView` reads to emit the
 * `bundesland=<token>` text line `loadProjectPromptView` above serves.
 *
 * Backlog T3-9 follow-up (2026-07-16, user-mandated): jurisdiction is a
 * cross-cutting request fact and must travel STRUCTURED on the
 * `X-Grid-Request-Context` envelope, not be re-parsed out of that prompt
 * text — this is the read producers resolve `GridRequestContextInput.bundesland`
 * from. Returns `null` for no project, no fact, or a value outside the
 * validated intake vocabulary (a stale/corrupt row must never leak an
 * unvalidated token onto the wire).
 */
export async function loadProjectBundesland(projectId: string | undefined): Promise<string | null> {
  if (!projectId) return null

  return getCached(`bundesland:${projectId}`, PROMPT_VIEW_CACHE_TTL_MS, async () => {
    const db = getDb()
    const [project] = await db
      .select({ profile: projects.profile })
      .from(projects)
      .where(eq(projects.id, projectId))
      .limit(1)
    const value = project?.profile?.facts?.bundesland?.value
    return typeof value === 'string' && isValidBundeslandToken(value) ? value : null
  })
}

export function buildProjectPromptView(profile: ProjectProfile): string {
  const normalized = ProjectProfileSchema.parse(profile)
  const sections: string[][] = [['PROJECT_CONTEXT v1']]

  const factKeys = Object.keys(normalized.facts).sort()
  if (factKeys.length > 0) {
    sections.push([
      'confirmed:',
      ...factKeys.map((key) => `- ${formatPromptToken(key)}=${formatPromptValue(normalized.facts[key].value)}`),
    ])
  }

  const goalKeys = Object.keys(normalized.goals).sort()
  if (goalKeys.length > 0) {
    sections.push([
      'goals:',
      ...goalKeys.map((key) => `- ${formatPromptToken(key)}=${formatPromptValue(normalized.goals[key])}`),
    ])
  }

  const unknowns = [...normalized.unknowns].sort()
  if (unknowns.length > 0) {
    sections.push(['unknown:', ...unknowns.map((unknown) => `- ${formatPromptToken(unknown)}`)])
  }

  const assumptionKeys = Object.keys(normalized.assumptions).sort()
  if (assumptionKeys.length > 0) {
    sections.push([
      'assumptions:',
      ...assumptionKeys.map((key) => `- ${formatPromptToken(key)}=${formatPromptValue(normalized.assumptions[key].value)}`),
    ])
  }

  return sections.map((section) => section.join('\n')).join('\n\n')
}

export function buildProjectProfileDisplay(
  profile: ProjectProfile,
  // The AI summary is generated by a separate async call (POST /generate-summary)
  // and stored on profileDisplay.summary. Rebuilding the display from the raw
  // profile (on every save/patch) must PRESERVE that summary rather than wiping
  // it -- otherwise any chat-driven profile edit permanently blanks the Project
  // Brief prose until the next full intake save.
  previousSummary = '',
): ProjectProfileDisplay {
  const normalized = ProjectProfileSchema.parse(profile)
  const brief = buildProjectBriefView(normalized)

  return {
    title: 'Project profile',
    summary: previousSummary,
    // Human-readable, intake-ordered: question labels ("Building class") and
    // option labels ("Residential") instead of raw keys/enum values.
    keyFacts: brief.groups.flatMap((group) =>
      group.facts.map((fact) => ({ label: fact.label, value: fact.value })),
    ),
    missingInfo: brief.missing.map((item) => item.label),
  }
}

function formatPromptToken(value: string): string {
  return isSafePromptToken(value) ? value : JSON.stringify(value).replace(/[\u0080-\u009f\u2028\u2029]/g, escapeLineSeparator)
}

function formatPromptValue(value: ProjectPrimitiveValue): string {
  if (typeof value === 'string') {
    return formatPromptToken(value)
  }

  return String(value)
}

function isSafePromptToken(value: string): boolean {
  return !/[\u0000-\u001f\u007f-\u009f\u2028\u2029]/.test(value)
}

function escapeLineSeparator(value: string): string {
  return `\\u${value.charCodeAt(0).toString(16).padStart(4, '0')}`
}
