/**
 * Riso art by id: the only way a page reaches a file in `public/art/`.
 *
 * `src/data/art.json` is generated by `art/riso/export.mjs` from each work's
 * JOBS table (`art/riso/<work>/index.html`). An id is `<work>/<plate>/<format>`,
 * e.g. `tafeln/stuetzen/plate`. `ArtId` is the union of the ids in that file,
 * so `astro check` refuses one that does not exist.
 *
 * The files are screened bitmaps baked at their display size. Show one only in
 * a slot of its CSS size (`width` x `height`), or at an integer fraction of
 * it, with the densities as `srcset`; never with `object-fit` or a width of
 * your own: resampling a halftone screen makes moiré.
 */
import manifest from '../data/art.json'
import type { Locale } from '../i18n/ui'

export type ArtId = keyof typeof manifest.art

export interface ArtFile {
  density: number
  src: string
  width: number
  height: number
}

export interface Art {
  work: string
  plate: string
  format: string
  /** The plate's roman numeral, or null for formats drawn without one. */
  numeral: string | null
  /** CSS size of the slot: the 1x file's pixels. */
  width: number
  height: number
  alt: Record<Locale, string>
  caption?: Record<Locale, string>
  files: ArtFile[]
}

const ART: Record<ArtId, Art> = manifest.art

export function art(id: ArtId): Art {
  const entry = ART[id]
  if (!entry) throw new Error(`art id "${id}" is not in src/data/art.json; run node art/riso/export.mjs`)
  return entry
}

/** The file for one density, falling back to the 1x file. */
export function artFile(a: Art, density = 1): ArtFile {
  return a.files.find((f) => f.density === density) ?? a.files[0]
}

/** `srcset` with width descriptors (`… 720w, … 1440w`), for a slot with `sizes`. */
export function artSrcset(a: Art): string {
  return a.files.map((f) => `${f.src} ${f.width}w`).join(', ')
}
