import type { CSSProperties, JSX } from 'react'

import { artImage, type ArtId } from '@/lib/art'
import { cn } from '@/lib/utils'

/**
 * A Piloti riso print (the picture language of the public site), by art id.
 *
 * The print is a halftone screen on warm paper `#F4F2E8`, exported at the
 * exact pixel size of its slot. Two rules follow from that:
 *
 * - **Native size only.** It is shown at its CSS size from `sm` up and at
 *   exactly half below it (a phone column is narrower than 320 px), never at a
 *   width of the layout's choosing: any other scale resamples the dot screen
 *   into moiré. So no `next/image` (it re-encodes and resizes), no
 *   `max-width: 100%`, no `object-fit`.
 * - **Paper, not ink.** The print is a sheet, so it has the sheet's rounded
 *   corners. In light mode its paper sits on the app's warm paper plane and
 *   needs nothing more. In dark mode it is not inverted or tinted: it is a
 *   printed sheet lying on the charcoal, so it takes the raised-plane shadow
 *   and is dimmed a step so a bright square does not glare out of a dark page.
 *
 * Decorative: every placement stands next to a heading that says what the
 * picture says, so it carries empty alt and stays out of the accessibility tree.
 * Art ids come from `src/lib/art/art.json`, generated by the riso harness in
 * `frontends/web/art/riso` (the `vignetten` work).
 */
export function RisoPrint({ id, className }: { id: ArtId; className?: string }): JSX.Element {
  const img = artImage(id)
  // The slot width drives both the CSS width and `sizes`, so the two can never disagree.
  const style = {
    '--art-w': `${img.width}px`,
    '--art-w-half': `${img.width / 2}px`,
  } as CSSProperties
  return (
    // eslint-disable-next-line @next/next/no-img-element -- a halftone must reach the screen unresampled; next/image re-encodes and resizes
    <img
      src={img.src}
      srcSet={img.srcSet}
      sizes={`(min-width: 640px) ${img.width}px, ${img.width / 2}px`}
      width={img.width}
      height={img.height}
      alt=""
      aria-hidden="true"
      decoding="async"
      draggable={false}
      style={style}
      className={cn(
        'w-(--art-w-half) sm:w-(--art-w) block h-auto max-w-none shrink-0 select-none rounded-md',
        'dark:shadow-sm dark:brightness-[0.92]',
        className
      )}
    />
  )
}
