// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { BackendTrafficPolicyArgs } from "./backendTrafficPolicy";
export type BackendTrafficPolicy = import("./backendTrafficPolicy").BackendTrafficPolicy;
export const BackendTrafficPolicy: typeof import("./backendTrafficPolicy").BackendTrafficPolicy = null as any;
utilities.lazyLoad(exports, ["BackendTrafficPolicy"], () => require("./backendTrafficPolicy"));

export { BackendTrafficPolicyListArgs } from "./backendTrafficPolicyList";
export type BackendTrafficPolicyList = import("./backendTrafficPolicyList").BackendTrafficPolicyList;
export const BackendTrafficPolicyList: typeof import("./backendTrafficPolicyList").BackendTrafficPolicyList = null as any;
utilities.lazyLoad(exports, ["BackendTrafficPolicyList"], () => require("./backendTrafficPolicyList"));

export { BackendTrafficPolicyPatchArgs } from "./backendTrafficPolicyPatch";
export type BackendTrafficPolicyPatch = import("./backendTrafficPolicyPatch").BackendTrafficPolicyPatch;
export const BackendTrafficPolicyPatch: typeof import("./backendTrafficPolicyPatch").BackendTrafficPolicyPatch = null as any;
utilities.lazyLoad(exports, ["BackendTrafficPolicyPatch"], () => require("./backendTrafficPolicyPatch"));

export { ClientTrafficPolicyArgs } from "./clientTrafficPolicy";
export type ClientTrafficPolicy = import("./clientTrafficPolicy").ClientTrafficPolicy;
export const ClientTrafficPolicy: typeof import("./clientTrafficPolicy").ClientTrafficPolicy = null as any;
utilities.lazyLoad(exports, ["ClientTrafficPolicy"], () => require("./clientTrafficPolicy"));

export { ClientTrafficPolicyListArgs } from "./clientTrafficPolicyList";
export type ClientTrafficPolicyList = import("./clientTrafficPolicyList").ClientTrafficPolicyList;
export const ClientTrafficPolicyList: typeof import("./clientTrafficPolicyList").ClientTrafficPolicyList = null as any;
utilities.lazyLoad(exports, ["ClientTrafficPolicyList"], () => require("./clientTrafficPolicyList"));

export { ClientTrafficPolicyPatchArgs } from "./clientTrafficPolicyPatch";
export type ClientTrafficPolicyPatch = import("./clientTrafficPolicyPatch").ClientTrafficPolicyPatch;
export const ClientTrafficPolicyPatch: typeof import("./clientTrafficPolicyPatch").ClientTrafficPolicyPatch = null as any;
utilities.lazyLoad(exports, ["ClientTrafficPolicyPatch"], () => require("./clientTrafficPolicyPatch"));

export { EnvoyProxyArgs } from "./envoyProxy";
export type EnvoyProxy = import("./envoyProxy").EnvoyProxy;
export const EnvoyProxy: typeof import("./envoyProxy").EnvoyProxy = null as any;
utilities.lazyLoad(exports, ["EnvoyProxy"], () => require("./envoyProxy"));

export { EnvoyProxyListArgs } from "./envoyProxyList";
export type EnvoyProxyList = import("./envoyProxyList").EnvoyProxyList;
export const EnvoyProxyList: typeof import("./envoyProxyList").EnvoyProxyList = null as any;
utilities.lazyLoad(exports, ["EnvoyProxyList"], () => require("./envoyProxyList"));

export { EnvoyProxyPatchArgs } from "./envoyProxyPatch";
export type EnvoyProxyPatch = import("./envoyProxyPatch").EnvoyProxyPatch;
export const EnvoyProxyPatch: typeof import("./envoyProxyPatch").EnvoyProxyPatch = null as any;
utilities.lazyLoad(exports, ["EnvoyProxyPatch"], () => require("./envoyProxyPatch"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:gateway.envoyproxy.io/v1alpha1:BackendTrafficPolicy":
                return new BackendTrafficPolicy(name, <any>undefined, { urn })
            case "kubernetes:gateway.envoyproxy.io/v1alpha1:BackendTrafficPolicyList":
                return new BackendTrafficPolicyList(name, <any>undefined, { urn })
            case "kubernetes:gateway.envoyproxy.io/v1alpha1:BackendTrafficPolicyPatch":
                return new BackendTrafficPolicyPatch(name, <any>undefined, { urn })
            case "kubernetes:gateway.envoyproxy.io/v1alpha1:ClientTrafficPolicy":
                return new ClientTrafficPolicy(name, <any>undefined, { urn })
            case "kubernetes:gateway.envoyproxy.io/v1alpha1:ClientTrafficPolicyList":
                return new ClientTrafficPolicyList(name, <any>undefined, { urn })
            case "kubernetes:gateway.envoyproxy.io/v1alpha1:ClientTrafficPolicyPatch":
                return new ClientTrafficPolicyPatch(name, <any>undefined, { urn })
            case "kubernetes:gateway.envoyproxy.io/v1alpha1:EnvoyProxy":
                return new EnvoyProxy(name, <any>undefined, { urn })
            case "kubernetes:gateway.envoyproxy.io/v1alpha1:EnvoyProxyList":
                return new EnvoyProxyList(name, <any>undefined, { urn })
            case "kubernetes:gateway.envoyproxy.io/v1alpha1:EnvoyProxyPatch":
                return new EnvoyProxyPatch(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("crds", "gateway.envoyproxy.io/v1alpha1", _module)
