"""Render the fixture office's permit records with the PRODUCTION pen: ``precedent/permits.json``.

The precedent eval's fixture BFF (``fixture_bff.py``) answers ``permits`` in the
cross-project search from this file, as production answers them from the rows
the ingest wrote. Those rows come from ``extract_permit_record``, a model with a
strict schema reading the document, so the fixture's records must too: a record
written by hand would test the agent against what its author thinks the pen
says, and hide the day the pen reads a Bescheid differently. This runs the pen
over every document of ``office.json`` the ingest's own type decision tagged
``Bescheid`` (``is_bescheid``) and writes what it returned.

    PYTHONPATH=src .venv/bin/python scripts/turn_census/render_fixture_permits.py

Needs the network and an OpenRouter key (``BACKFILL_SUMMARY_API_KEY``, or the
provider key its base URL implies). The model is the one the backfill builds:
the ingest's summary model, pinned to zero-data-retention endpoints through the
OpenRouter seam (``PLATFORM_FIXED``). Nothing is written when a document yields
no record, so an outage cannot commit half a fixture; re-run it.

Commit the output with the change that moved the pen (its prompt, its schema or
the model). Never edit it by hand: a record the pen gets wrong is a finding
about the pen.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
# The backfill builds the platform-fixed extraction model; one place knows how.
sys.path.insert(0, str(ROOT / "scripts"))

from backfill_permit_records import build_extraction_llm  # noqa: E402

from aiq_agent.common.openrouter import PLATFORM_FIXED  # noqa: E402
from aiq_agent.common.openrouter import pin_chat_model  # noqa: E402
from aiq_agent.knowledge.permit_extraction import extract_permit_record  # noqa: E402
from aiq_agent.knowledge.permit_extraction import is_bescheid  # noqa: E402
from aiq_agent.knowledge.permit_extraction import llm_model_name  # noqa: E402
from aiq_agent.knowledge.permit_extraction import pages_with_markers  # noqa: E402

FIXTURES = ROOT / "frontends" / "ui" / "tests" / "fixtures" / "precedent"
OFFICE = FIXTURES / "office.json"
OUTPUT = FIXTURES / "permits.json"
COMMENT = (
    "Generated by scripts/turn_census/render_fixture_permits.py: the production pen "
    "(aiq_agent.knowledge.permit_extraction.extract_permit_record) over each Bescheid of office.json; "
    "do not edit by hand."
)


def render(llm: object, office: dict) -> tuple[dict[str, dict], list[str]]:
    """(records by document id, the documents that yielded none), for every Bescheid of the office."""
    records: dict[str, dict] = {}
    missing: list[str] = []
    for project in office["projects"]:
        for document in project.get("documents") or []:
            if not is_bescheid(document.get("tags")):
                continue
            text = pages_with_markers([(document.get("page", 1), document["text"])])
            record = extract_permit_record(text, llm, file_name=document["filename"])
            if record is None:
                missing.append(document["documentId"])
                continue
            records[document["documentId"]] = record.to_wire()
    return records, missing


def main() -> int:
    office = json.loads(OFFICE.read_text(encoding="utf-8"))
    llm = pin_chat_model(build_extraction_llm(), PLATFORM_FIXED)
    records, missing = render(llm, office)
    if missing:
        print(
            f"No record for {', '.join(missing)}: nothing written; the pen failed or judged them no notice.",
            file=sys.stderr,
        )
        return 1
    document = {"$comment": COMMENT, "model": llm_model_name(llm), "records": records}
    OUTPUT.write_text(json.dumps(document, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    for document_id, record in records.items():
        print(f"{document_id}: {record['kind']}, {record['authority']}, {len(record['requirements'])} requirement(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
