#!/usr/bin/env node
/*
 * The downloads: every riso file that no page of this site shows, published
 * into public/downloads/ so the unlisted image page (src/lib/unlisted.ts) can
 * hand it out. Two kinds of job land here, read from the JOBS tables:
 *
 *   out  LinkedIn, deck, social, postcard and its print separations. Exported
 *        to the gitignored art/riso/out/<work>/, so a deploy never has them;
 *        this copies them in.
 *   app  the product app's vignettes. They live in frontends/ui/public/art/,
 *        which the site's image (built from frontends/web alone) cannot reach.
 *
 *   node art/riso/downloads.mjs              # publish what exists, rewrite src/data/downloads.json
 *   node art/riso/downloads.mjs --manifest   # only rewrite the manifest
 *
 * export.mjs runs this at its end, so a new or renamed out job reaches the
 * page with the export that made it. check.mjs holds the result to the JOBS
 * tables: a job without its download, an orphan, a stale manifest.
 *
 * Encoding. The pre-commit hook refuses files above 1 MB. A PNG within that is
 * copied byte for byte (lossless). A larger one (the 1920 slides, the postcard
 * composite) becomes a JPEG at quality 95 (lower in steps of 2, down to 85, only
 * while it is still over the limit) with 4:4:4 chroma: every slide tool,
 * LinkedIn and every print shop reads JPEG, where WebP is refused by some of
 * them, and lossless WebP stays above 1 MB for the postcards. Measured against
 * the PNG: mean error 0.6–1.9 levels of 255. The separations are what a press
 * prints from, so they are never re-encoded: grayscale PNG, or a failure.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';
import { DESTS, MAX_BYTES, OUT, WEB, args, evaluateWork, fileVersion, listWorks, roman } from './kit.mjs';

export const DOWNLOADS = path.join(WEB, 'public', 'downloads');
export const DOWNLOADS_MANIFEST = path.join(WEB, 'src', 'data', 'downloads.json');
/** The job destinations the site does not already serve from public/art/. */
const KINDS = new Set(['out', 'app']);

const stem = (file) => file.replace(/\.\w+$/, '');
const sheetName = (job) => `${stem(job.file)}-separations.json`;

/** Where the exporter left a job's file: art/riso/out/<work>/, or the app's public/art/. */
function sourceOf(job, file = job.file) {
  return job.dest === 'app' ? path.join(DESTS.app.art, file) : path.join(OUT, job.work, file);
}

/** The published name: the job's own, or .jpg when the PNG had to be re-encoded. */
function publishedOf(job) {
  for (const name of [job.file, `${stem(job.file)}.jpg`]) if (fs.existsSync(path.join(DOWNLOADS, name))) return name;
  return null;
}

/**
 * The downloads manifest: one entry per art id whose job goes `out` or `app`,
 * shaped like src/data/art.json (files per density), plus `separations` for a
 * postcard: the print shop's sheet and one grayscale PNG per ink. A pure
 * function of the JOBS tables and the bytes in public/downloads/, so check.mjs
 * can rebuild and compare it. A job not published yet is left out and listed
 * in `missing`.
 */
export function downloadsFrom(jobsByWork) {
  const art = {}, missing = [], expected = new Set();
  const src = (name) => `/downloads/${name}?v=${fileVersion(path.join(DOWNLOADS, name))}`;
  for (const job of jobsByWork.flat().filter((j) => KINDS.has(j.dest))) {
    const name = publishedOf(job);
    if (!name) { missing.push({ id: job.id, file: job.file }); continue; }
    expected.add(name);
    const e = art[job.id] || (art[job.id] = {
      work: job.work, plate: job.plate, format: job.format, dest: job.dest,
      numeral: job.number ? roman(job.number) : null,
      width: 0, height: 0,
      alt: job.alt,
      ...(job.caption ? { caption: job.caption } : {}),
      files: [],
    });
    e.files.push({ density: job.density, src: src(name), width: job.w, height: job.h });
    if (job.density === 1) { e.width = job.w; e.height = job.h; }
    if (!job.separations) continue;
    const sheetFile = path.join(DOWNLOADS, sheetName(job));
    if (!fs.existsSync(sheetFile)) { missing.push({ id: job.id, file: sheetName(job) }); continue; }
    const sheet = JSON.parse(fs.readFileSync(sheetFile, 'utf8'));
    expected.add(sheetName(job));
    e.separations = {
      sheet: src(sheetName(job)),
      inks: sheet.inks.map((ink) => {
        expected.add(ink.file);
        if (!fs.existsSync(path.join(DOWNLOADS, ink.file))) missing.push({ id: job.id, file: ink.file });
        return { order: ink.order, ink: ink.ink, drum: ink.drum, hex: ink.hex, src: src(ink.file), width: job.w, height: job.h };
      }),
    };
  }
  const sorted = Object.fromEntries(Object.keys(art).sort().map((k) => [k, art[k]]));
  return {
    manifest: {
      $comment: 'Generated by art/riso/downloads.mjs (run by export.mjs) from each work\'s JOBS table and the bytes in public/downloads/: the riso files no page shows, for the unlisted image page. Do not edit.',
      art: sorted,
    },
    missing,
    expected,
  };
}

export const downloadsText = (m) => JSON.stringify(m, null, 2) + '\n';

/** Write `bytes` to public/downloads/<name> unless it already holds them. */
function put(name, bytes) {
  const file = path.join(DOWNLOADS, name);
  if (fs.existsSync(file) && fs.readFileSync(file).equals(bytes)) return false;
  fs.writeFileSync(file, bytes);
  return true;
}

/** A PNG within the limit as it is; a larger one as JPEG q95 4:4:4. */
async function encodeFor(source) {
  const png = fs.readFileSync(source);
  if (png.length <= MAX_BYTES) return { ext: 'png', bytes: png };
  // 95 unless that is still over the limit (the densest slide is at 0.95 of it)
  let jpeg;
  for (let quality = 95; quality >= 85; quality -= 2) {
    jpeg = await sharp(png).flatten({ background: '#ffffff' })
      .keepMetadata() // keeps the postcard's 300 dpi
      .jpeg({ quality, chromaSubsampling: '4:4:4', mozjpeg: true }).toBuffer();
    if (jpeg.length <= MAX_BYTES) break;
  }
  return { ext: 'jpg', bytes: jpeg };
}

/**
 * Copy (or re-encode) every out and app job whose source exists into
 * public/downloads/, drop what no job names any more, rewrite the manifest.
 * A job whose source is absent keeps the copy already published, so a
 * checkout without art/riso/out/ changes nothing.
 */
export async function publishDownloads({ log = console.log } = {}) {
  const jobsByWork = listWorks().map((w) => evaluateWork(w).jobs);
  fs.mkdirSync(DOWNLOADS, { recursive: true });
  let failures = 0;
  const kb = (n) => `${(n / 1024).toFixed(0)} KB`;
  for (const job of jobsByWork.flat().filter((j) => KINDS.has(j.dest))) {
    const source = sourceOf(job);
    if (!fs.existsSync(source)) continue;
    const { ext, bytes } = job.encode === 'png' ? await encodeFor(source) : { ext: path.extname(job.file).slice(1), bytes: fs.readFileSync(source) };
    const name = `${stem(job.file)}.${ext}`;
    // the other extension, from an earlier publish, is stale now
    for (const old of [job.file, `${stem(job.file)}.jpg`]) if (old !== name) fs.rmSync(path.join(DOWNLOADS, old), { force: true });
    if (put(name, bytes)) log(`  downloads/${name}  ${kb(bytes.length)}${ext === 'jpg' ? '  (JPEG q95: the PNG is over 1 MB)' : ''}`);
    if (bytes.length > MAX_BYTES) { failures++; log(`  downloads/${name} is over 1 MB: the commit hook will refuse it`); }
    if (!job.separations) continue;
    const sheet = JSON.parse(fs.readFileSync(sourceOf(job, sheetName(job)), 'utf8'));
    for (const ink of sheet.inks) {
      const sep = fs.readFileSync(sourceOf(job, ink.file));
      if (sep.length > MAX_BYTES) { failures++; log(`  ${ink.file} is over 1 MB, and a separation is never re-encoded`); continue; }
      if (put(ink.file, sep)) log(`  downloads/${ink.file}  ${kb(sep.length)}`);
    }
    // the sheet names the composite as published
    put(sheetName(job), Buffer.from(JSON.stringify({ ...sheet, file: name }, null, 2) + '\n'));
  }
  const { manifest, missing, expected } = downloadsFrom(jobsByWork);
  for (const f of fs.readdirSync(DOWNLOADS)) {
    if (!expected.has(f)) { fs.rmSync(path.join(DOWNLOADS, f)); log(`  removed downloads/${f}: no job names it`); }
  }
  // an orphan is in no entry, so removing it leaves the manifest as derived
  const text = downloadsText(manifest);
  const before = fs.existsSync(DOWNLOADS_MANIFEST) ? fs.readFileSync(DOWNLOADS_MANIFEST, 'utf8') : '';
  if (text !== before) fs.writeFileSync(DOWNLOADS_MANIFEST, text);
  if (missing.length) log(`not exported yet, so not downloadable: ${missing.map((m) => m.file).join(', ')}\n  run: node art/riso/export.mjs --dest out`);
  log(`manifest ${path.relative(process.cwd(), DOWNLOADS_MANIFEST)}: ${Object.keys(manifest.art).length} ids${text === before ? ', unchanged' : ', rewritten'}`);
  return { failures, missing };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  const a = args(process.argv.slice(2));
  if (a.manifest) {
    const text = downloadsText(downloadsFrom(listWorks().map((w) => evaluateWork(w).jobs)).manifest);
    fs.writeFileSync(DOWNLOADS_MANIFEST, text);
    console.log(`manifest ${path.relative(process.cwd(), DOWNLOADS_MANIFEST)} rewritten`);
  } else {
    const { failures } = await publishDownloads();
    if (failures) process.exit(1);
  }
}
