/**
 * Riso art in the app, by id.
 *
 * `art.json` is generated by `frontends/web/art/riso/export.mjs` from the riso
 * works (formats whose destination is `app`), next to the files it names in
 * `public/art/`. Never edit either by hand: change the work, re-export, and
 * `node art/riso/check.mjs` (web's `npm run check`) holds both to the source.
 *
 * `ArtId` is the manifest's keys, so an id that is not exported does not
 * compile. Every `src` carries `?v=<hash>`, which changes with the bytes.
 */

import manifest from './art.json'

export type ArtId = keyof typeof manifest.art

export interface ArtFile {
  density: number
  src: string
  width: number
  height: number
}

export interface ArtEntry {
  /** CSS size of the slot, which is the 1x file's pixel size. */
  width: number
  height: number
  files: readonly ArtFile[]
}

export function art(id: ArtId): ArtEntry {
  return manifest.art[id]
}

/**
 * `<img>` attributes for a print.
 *
 * A halftone screen resampled to any other size turns into moiré, so a print
 * is shown only at its own size or exactly half of it. Width descriptors let
 * the browser take the file that lands 1:1 on device pixels: at full size the
 * 1x file on a 1x screen and the 2x file on a 2x screen, at half size the 1x
 * file on a 2x screen. `sizes` is the caller's, because only it knows the slot.
 */
export function artImage(id: ArtId): {
  src: string
  srcSet: string
  width: number
  height: number
} {
  const a = art(id)
  const one = a.files.find((f) => f.density === 1) ?? a.files[0]
  return {
    src: one.src,
    srcSet: a.files.map((f) => `${f.src} ${f.width}w`).join(', '),
    width: a.width,
    height: a.height,
  }
}
